export const data = [
  {
    question: "Which country has the largest population in the world?",
    option1: "India",
    option2: "United States",
    option3: "China",
    option4: "Russia",
    ans: 3,
  },
  {
    question: "Which continent is known as the 'Dark Continent'?",
    option1: "Asia",
    option2: "Africa",
    option3: "Europe",
    option4: "South America",
    ans: 2,
  },
  {
    question: "What is the capital of France?",
    option1: "Berlin",
    option2: "Madrid",
    option3: "Paris",
    option4: "Rome",
    ans: 3,
  },
  {
    question: "Which country is the Great Barrier Reef located in?",
    option1: "Australia",
    option2: "South Africa",
    option3: "Brazil",
    option4: "United States",
    ans: 1,
  },
  {
    question: "Which desert is the largest in the world?",
    option1: "Sahara Desert",
    option2: "Kalahari Desert",
    option3: "Arabian Desert",
    option4: "Gobi Desert",
    ans: 1,
  },
  {
    question: "Which city is known as the 'City of Angels'?",
    option1: "New York City",
    option2: "Los Angeles",
    option3: "Miami",
    option4: "San Francisco",
    ans: 2,
  },
  {
    question: "What is the smallest country in the world?",
    option1: "Monaco",
    option2: "Vatican City",
    option3: "San Marino",
    option4: "Liechtenstein",
    ans: 2,
  },
  {
    question: "Which river is the longest in the world?",
    option1: "Amazon River",
    option2: "Nile River",
    option3: "Yangtze River",
    option4: "Mississippi River",
    ans: 2,
  },
  {
    question: "What is the largest island in the world?",
    option1: "Greenland",
    option2: "Australia",
    option3: "New Guinea",
    option4: "Borneo",
    ans: 1,
  },
  {
    question: "Which country is known as the 'Land of the Rising Sun'?",
    option1: "South Korea",
    option2: "Japan",
    option3: "China",
    option4: "Thailand",
    ans: 2,
  },
];
